apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: ceq-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceq-product

  template:
    metadata:
      labels:
        app: ceq-product

    spec:
      containers:
      - name: products-service
        image: aneei/ceq-products:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 7000

        env:

        #################################################
        # Database configuration
        #################################################

        - name: DB_NAME
          value: "Shopping_Cart"

        - name: DB_USER
          value: "admin"

        - name: DB_PASSWORD
          value: "rdsadmin"

        - name: DIALECT
          value: "mysql"

        - name: DB_HOST
          value: "dbsnapshot.cf6c8yamwday.us-east-1.rds.amazonaws.com"

        #################################################
        # Service communication
        #################################################

        - name: USER_RESPONSE
          value: "http://users-service:8000"

        - name: PRODUCT_RESPONSE
          value: "http://products-service:7001"

        #################################################
        # OpenTelemetry configuration
        #################################################

        - name: OTEL_SERVICE_NAME
          value: "products-service"

        # - name: OTEL_RESOURCE_ATTRIBUTES
        #   value: "service.name=user-service,k8s.cluster.name=shopping-cart-coralogix-otel"

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-coralogix-opentelemetry-agent.coralogix-system.svc.cluster.local:4318"

        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"

        - name: OTEL_LOGS_EXPORTER
          value: "otlp"

        - name: OTEL_METRICS_EXPORTER
          value: "otlp"

        - name: OTEL_TRACES_EXPORTER
          value: "otlp"

        #################################################
        # Resource limits (recommended)
        #################################################

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  labels:
    app: ceq-product

spec:
  type: LoadBalancer

  selector:
    app: ceq-product

  ports:
  - name: http
    port: 7001
    targetPort: 7001
    protocol: TCP