apiVersion: v1
kind: Service
metadata:
  name: az-ceq-ekart-users
  labels:
    app: az-ceq-ekart-users
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: az-ceq-ekart-users
  type: LoadBalancer