apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-ceq-ekart-cart
spec:
  selector:
    matchLabels:
      app: az-ceq-ekart-cart
  template:
    metadata:
      labels:
        app: az-ceq-ekart-cart
    spec:
      containers:
      - name: az-ceq-ekart-cart
        image: manikanta26/az_ceq_ekart_cart:v9
        env:
        - name: DB_NAME
          value: "shop_cart"
        - name: DB_USER
          value: "shopcart"
        - name: DB_HOST
          value: az-mysql-fs-ceq-in-ekart-server.mysql.database.azure.com
        - name: DB_PASSWORD
          value: "cloudeq@1234"
        - name: USER_RESPONSE
          value: http://52.249.235.129:8000
        - name: PRODUCT_RESPONSE
          value: http://4.255.7.91:7001

        ports:
        - containerPort: 8001
