apiVersion: v1
kind: Service
metadata:
  name: az-ceq-ekart-cart
  labels:
    app: az-ceq-ekart-cart
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: az-ceq-ekart-cart
  type: LoadBalancer