apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-ceq-ekart-orders
spec:
  selector:
    matchLabels:
      app: az-ceq-ekart-orders
  template:
    metadata:
      labels:
        app: az-ceq-ekart-orders
    spec:
      containers:
      - name: az-ceq-ekart-orders
        image: manikanta26/az_ceq_ekart_orders:v10
        env:
        - name: DB_NAME
          value: "shop_cart"
        - name: DB_USER
          value: "shopcart"
        - name: DB_HOST
          value: az-mysql-fs-ceq-in-ekart-server.mysql.database.azure.com
        - name: DB_PASSWORD
          value: "cloudeq@1234"
        - name: USER_RESPONSE
          value: http://52.249.235.129:8000
        - name: PRODUCT_RESPONSE
          value: "http://4.255.7.91:7001"
        - name: EMPTY_CART
          value: "http://172.171.139.178:8001"

        ports:
        - containerPort: 8002
