apiVersion: v1
kind: Service
metadata:
  name: az-ceq-ekart-product
  labels:
    app: az-ceq-ekart-product
spec:
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
  selector:
    app: az-ceq-ekart-product
  type: LoadBalancer